=== decedric/husky/ehealth_connector-validation/ehealth_connector-validation-service/src/main/java/configuration.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- =================================================================== -->
<!-- Configuration schema for Online-CDA-Validator                       -->
<!--                                                                     -->
<!-- History:                                                            -->
<!-- 2013.04.30: Laurent Millet, medshare GmbH (V1.0.0)                  -->
<!--                                                                     -->
<!-- =================================================================== -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0">

  <!-- =================================================================== -->
  <!-- The unique root element of the XML configuration file.              -->
  <!-- =================================================================== -->

  <xsd:element name="configuration" type="ConfigurationType">
    <xsd:annotation>
      <xsd:documentation>
        The unique root element of the XML configuration file.
      </xsd:documentation>
    </xsd:annotation>
  </xsd:element>

  <!-- =================================================================== -->
  <!-- The root type of the XML configuration file. It has an optional     -->
  <!-- baseDir attribute and must have exactly one schematron sub-element. -->
  <!-- =================================================================== -->

  <xsd:complexType name="ConfigurationType">
    <xsd:sequence>
      <xsd:element name="application" type="ApplicationType" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>
            The application related configuration.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="schematron" type="SchematronType">
        <xsd:annotation>
          <xsd:documentation>
            The Schematron related configuration. This mainly defines which
            rule-sets should be made available in the Online-Validator.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="baseDir" use="optional">
      <xsd:annotation>
        <xsd:documentation>
          The base directory. If specified, all non-absolute path specifications
          will be relative to this directory.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="ApplicationType">
    <xsd:sequence>
      <xsd:element name="downloads-url" type="xsd:string" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>
            URL of ELGA's main download page.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="jquery-theme" type="xsd:string" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>
            Name of the JQuery theme to use (without extension).
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="document-schema" type="xsd:string" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>
            The XSD Schema the input documents must conform.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pdf-level" type="xsd:string" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>
            The PDF Level used for Validation (1=PDF/A-1, 2=PDF/A-2, 3=PDF/A-3)
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pdf-reporting-level" type="xsd:string" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>
            0 none Nothing is reported 
            1 errors Errors only are reported 
            2 warnings Errors and warnings are reported 
            3 information Errors, warnings and information messages are reported
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="license-key" type="xsd:string" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>
            The license-key for the pdf-tools software
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <!-- =================================================================== -->
  <!-- The Schematron element consists of one or many rule-set elements.   -->
  <!-- It has a mandatory dir attribute, which is used when the path       -->
  <!-- of a rule-set element is not absolute.                              -->
  <!-- =================================================================== -->

  <xsd:complexType name="SchematronType">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:annotation>
        <xsd:appinfo>
          <jxb:property name="ruleSets" />
        </xsd:appinfo>
      </xsd:annotation>
      <xsd:element name="rule-set" type="RuleSetType">
        <xsd:annotation>
          <xsd:documentation>
            Defines a single Schematron rule-set.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="dir" type="xsd:string" use="required">
      <xsd:annotation>
        <xsd:documentation>
          The root directory of the Schematron rule-sets. The specified path
          can either be absolute or relative to the base directory.
        </xsd:documentation>
        <xsd:appinfo>
          <jxb:property name="directory" />
        </xsd:appinfo>
      </xsd:annotation>
    </xsd:attribute>
  </xsd:complexType>

  <!-- =================================================================== -->
  <!-- The Rule-Set element has a mandatory file attribute and an optional -->
  <!-- oid attribute. A rule-set can have an optional display-name and a   -->
  <!-- description sub-element.                                            -->
  <!-- =================================================================== -->

  <xsd:complexType name="RuleSetType">
    <xsd:sequence>
      <xsd:element name="description" type="xsd:string" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>
            The description of the rule-set.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="display-name" type="xsd:string" minOccurs="0">
        <xsd:annotation>
          <xsd:documentation>
            The human readable name of the rule-set.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
	    <xsd:element name="templateId" type="xsd:string" minOccurs="0">
	      <xsd:annotation>
	        <xsd:documentation>
	          The root template ID of a source CDA document matching this rule-set.
	        </xsd:documentation>
	      </xsd:annotation>
	    </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="file" type="xsd:string" use="required">
      <xsd:annotation>
        <xsd:documentation>
          The path to the master Schematron file of this rule-set.
          The specified path can either be absolute or relative.
        </xsd:documentation>
        <xsd:appinfo>
          <jxb:property name="fileName" />
        </xsd:appinfo>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="persistable" type="xsd:boolean" default="true">
      <xsd:annotation>
        <xsd:documentation>
          Allows/disallows storing the transformed rule-set to the disk.
          This spares three transformation steps and significantly speeds
          up the creation of the validator.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="cacheable" type="xsd:boolean" default="true">
      <xsd:annotation>
        <xsd:documentation>
          Allows/disallows caching of the compiled validator stylesheet.
          This makes the validator stylesheet immediately available.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
  </xsd:complexType>

</xsd:schema>

=== decedric/husky/ehealth_connector-validation/ehealth_connector-validation-service/rsc/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- The base directory is set to be the parent folder of the configuration
file. -->
<configuration baseDir="rsc"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="configuration.xsd">
	
	<application>
		<document-schema>schema/CDA.xsd</document-schema>
		<!-- The PDF Level used for Validation:
		1a: PDF/A 1a, ISO 19005-1, Level A compliance
		1b: PDF/A 1b, ISO 19005-1, Level B compliance
		2a: PDF/A 2a, ISO 19005-2, Level A compliance
		2b: PDF/A 2b, ISO 19005-2, Level B compliance
		2u: PDF/A 2u, ISO 19005-2, Level U compliance
		3a: PDF/A 3a, ISO 19005-3, Level A compliance
		3b: PDF/A 3b, ISO 19005-3, Level B compliance
		3u: PDF/A 3u, ISO 19005-3, Level U compliance
		-->
		<pdf-level>1a</pdf-level>

		<!-- The level of validation result reporting:
		0: none Nothing is reported
		1: errors Errors are reported
		2: warnings Errors and warnings are reported
		3: information Error, warnings and information are reported
		-->
		<pdf-reporting-level>3</pdf-reporting-level>

		<!-- The license-key for the pdf-tools software -->
		<!-- Uncomment the license-key only if you pdf-tools installed -->

		<!-- <license-key>yourkey</license-key>  -->
	</application>


	<!-- The Schematrons are located at a path relative to the base directory. -->
	<schematron dir="schematron">

		<!-- Rule-Sets for Unit testing -->
		<rule-set file="miniCDA.sch">
			<description>Just for Unit tests</description>
			<display-name>miniCDA</display-name>
			<templateId>2.999</templateId>
		</rule-set>
	</schematron>

</configuration>

=== decedric/husky/ehealth_connector-validation/ehealth_connector-validation-service/rsc/config_elga.xml
<?xml version="1.0" encoding="UTF-8"?> <!-- The base directory is set to be the parent folder of the configuration 
	file. -->
<configuration baseDir="rsc"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="configuration.xsd">
	<application>
		<document-schema>schema/CDA_extELGA.xsd</document-schema>
		<!-- The PDF Level used for Validation (1=PDF/A-1, 2=PDF/A-2, 3=PDF/A-3) -->
		<pdf-level>1a</pdf-level>
		<!-- 0 none Nothing is reported 1 errors Errors only are reported 2 warnings 
			Errors and warnings are reported 3 information Errors, warnings and information 
			messages are reported -->
		<pdf-reporting-level>3</pdf-reporting-level>
		<!-- The license-key for the pdf-tools software -->
		<!-- Uncomment the license-key only if you pdf-tools installed -->
		<!-- <license-key>yourkey</license-key>  -->
	</application>
	<!-- The Schematrons are located at a path relative to the base directory. -->
	  <!--
  The Schematrons are located at a path relative to the base directory.
    -->
  <schematron dir="schematron">

    <!--
    ELGA's Rule-Sets with correct templateId set.
    -->
    <rule-set file="elga-cdabgd.sch">
      <description>Befund bildgebende Diagnostik</description>
      <display-name>Befund bildgebende Diagnostik</display-name>
      <templateId>1.2.40.0.34.11.5</templateId>
    </rule-set>
    <rule-set file="elga-cdaea.sch">
      <display-name>Entlassungsbrief ärztlich</display-name>
      <templateId>1.2.40.0.34.11.2</templateId>
    </rule-set>
    <rule-set file="elga-cdaep.sch">
      <display-name>Entlassungsbrief Pflege</display-name>
      <templateId>1.2.40.0.34.11.3</templateId>
    </rule-set>
    <rule-set file="elga-cdalab.sch">
      <display-name>Laborbefund</display-name>
      <templateId>1.2.40.0.34.11.4</templateId>
    </rule-set>
    <rule-set file="elga-cdaempr.sch">
      <display-name>e-Medikation Rezept</display-name>
      <templateId>1.2.40.0.34.11.8.1</templateId>
    </rule-set>
    <rule-set file="elga-cdaemdp.sch">
      <display-name>e-Medikation Abgabe</display-name>
      <templateId>1.2.40.0.34.11.8.2</templateId>
    </rule-set>
    <rule-set file="elga-cdaemml.sch">
      <display-name>e-Medikation Medikationsliste</display-name>
      <templateId>1.2.40.0.34.11.8.3</templateId>
    </rule-set>
    <rule-set file="elga-cdaempa.sch">
      <display-name>e-Medikation Pharmazeutische Empfehlung</display-name>
      <templateId>1.2.40.0.34.11.8.4</templateId>
    </rule-set>
  </schematron>

</configuration>
